import { ProductCardProps } from "@/components/global/Common-Card/Card"


// Weekly Deals Products
export const weeklyDealsProducts: ProductCardProps[] = [
  {
    id: "wd1",
    title: "Premium Cotton T-Shirt",
    image: "https://placehold.co/600x400.png",
    price: 39.99,
    discountPrice: 24.99,
    vendorName: "FashionBrand",
    badge: "discount",
    stock: "in-stock",
  },
  {
    id: "wd2",
    title: "Slim Fit Jeans",
    image: "https://placehold.co/600x400.png",
    price: 79.99,
    discountPrice: 49.99,
    vendorName: "DenimCo",
    badge: "discount",
    stock: "in-stock",
  },
  {
    id: "wd3",
    title: "Casual Sneakers",
    image: "https://placehold.co/600x400.png",
    price: 89.99,
    discountPrice: 59.99,
    vendorName: "FootwearPlus",
    badge: "hot-sale",
    stock: "low-stock",
  },
  {
    id: "wd4",
    title: "Summer Hat",
    image: "https://placehold.co/600x400.png",
    price: 29.99,
    discountPrice: 19.99,
    vendorName: "AccessoriesHub",
    badge: "discount",
    stock: "in-stock",
  },
  {
    id: "wd5",
    title: "Leather Belt",
    image: "https://placehold.co/600x400.png",
    price: 49.99,
    discountPrice: 34.99,
    vendorName: "LeatherCraft",
    badge: "discount",
    stock: "in-stock",
  },
]

// Trending Products
export const trendingProducts: ProductCardProps[] = [
  {
    id: "tr1",
    title: "Oversized Graphic Tee",
    image: "https://placehold.co/600x400.png",
    price: 44.99,
    vendorName: "StreetStyle",
    badge: "hot-sale",
    stock: "in-stock",
  },
  {
    id: "tr2",
    title: "Cargo Pants",
    image: "https://placehold.co/600x400.png",
    price: 69.99,
    vendorName: "UrbanThreads",
    badge: "hot-sale",
    stock: "in-stock",
  },
  {
    id: "tr3",
    title: "Platform Sandals",
    image: "https://placehold.co/600x400.png",
    price: 79.99,
    vendorName: "FootwearPlus",
    badge: "hot-sale",
    stock: "in-stock",
  },
  {
    id: "tr4",
    title: "Bucket Hat",
    image: "https://placehold.co/600x400.png",
    price: 34.99,
    vendorName: "AccessoriesHub",
    badge: "hot-sale",
    stock: "in-stock",
  },
  {
    id: "tr5",
    title: "Crossbody Bag",
    image: "https://placehold.co/600x400.png",
    price: 59.99,
    vendorName: "BagWorld",
    badge: "hot-sale",
    stock: "in-stock",
  },
  {
    id: "tr6",
    title: "Statement Earrings",
    image: "https://placehold.co/600x400.png",
    price: 24.99,
    vendorName: "JewelryBox",
    badge: "hot-sale",
    stock: "in-stock",
  },
  {
    id: "tr7",
    title: "Vintage Sunglasses",
    image: "https://placehold.co/600x400.png",
    price: 39.99,
    vendorName: "RetroEyewear",
    badge: "hot-sale",
    stock: "in-stock",
  },
  {
    id: "tr8",
    title: "Chunky Sneakers",
    image: "https://placehold.co/600x400.png",
    price: 99.99,
    vendorName: "KicksMaster",
    badge: "hot-sale",
    stock: "low-stock",
  },
]

// New Arrivals Products
export const newArrivalsProducts: ProductCardProps[] = [
  {
    id: "na1",
    title: "Linen Blend Shirt",
    image: "https://placehold.co/600x400.png",
    price: 54.99,
    vendorName: "SummerEssentials",
    stock: "in-stock",
  },
  {
    id: "na2",
    title: "Relaxed Fit Shorts",
    image: "https://placehold.co/600x400.png",
    price: 49.99,
    vendorName: "CasualWear",
    stock: "in-stock",
  },
  {
    id: "na3",
    title: "Strappy Sandals",
    image: "https://placehold.co/600x400.png",
    price: 64.99,
    vendorName: "FootwearPlus",
    stock: "in-stock",
  },
  {
    id: "na4",
    title: "Straw Beach Bag",
    image: "https://placehold.co/600x400.png",
    price: 39.99,
    vendorName: "BeachStyle",
    stock: "in-stock",
  },
  {
    id: "na5",
    title: "Printed Maxi Dress",
    image: "https://placehold.co/600x400.png",
    price: 79.99,
    vendorName: "DressCollection",
    stock: "in-stock",
  },
]

// Best Seller Products
export const bestSellerProducts: ProductCardProps[] = [
  {
    id: "bs1",
    title: "Classic White Tee",
    image: "https://placehold.co/600x400.png",
    price: 29.99,
    vendorName: "BasicEssentials",
    badge: "unique",
    stock: "in-stock",
  },
  {
    id: "bs2",
    title: "Slim Fit Chinos",
    image: "https://placehold.co/600x400.png",
    price: 59.99,
    vendorName: "MensWardrobe",
    badge: "unique",
    stock: "in-stock",
  },
  {
    id: "bs3",
    title: "Leather Sneakers",
    image: "https://placehold.co/600x400.png",
    price: 89.99,
    vendorName: "PremiumFootwear",
    badge: "unique",
    stock: "in-stock",
  },
  {
    id: "bs4",
    title: "Denim Jacket",
    image: "https://placehold.co/600x400.png",
    price: 99.99,
    vendorName: "DenimCo",
    badge: "unique",
    stock: "in-stock",
  },
  {
    id: "bs5",
    title: "Aviator Sunglasses",
    image: "https://placehold.co/600x400.png",
    price: 49.99,
    vendorName: "EyewearLuxe",
    badge: "unique",
    stock: "in-stock",
  },
]

// Seasonal Products
export const seasonalProducts = {
  summer: [
    {
      id: "ss1",
      title: "Linen Shorts",
      image: "https://placehold.co/600x400.png",
      price: 49.99,
      vendorName: "SummerEssentials",
      stock: "in-stock",
    },
    {
      id: "ss2",
      title: "Breathable Polo",
      image: "https://placehold.co/600x400.png",
      price: 39.99,
      vendorName: "CasualWear",
      stock: "in-stock",
    },
    {
      id: "ss3",
      title: "Straw Hat",
      image: "https://placehold.co/600x400.png",
      price: 29.99,
      vendorName: "AccessoriesHub",
      stock: "in-stock",
    },
    {
      id: "ss4",
      title: "Swim Shorts",
      image: "https://placehold.co/600x400.png",
      price: 44.99,
      vendorName: "BeachStyle",
      stock: "in-stock",
    },
    {
      id: "ss5",
      title: "Lightweight Tee",
      image: "https://placehold.co/600x400.png",
      price: 24.99,
      vendorName: "BasicEssentials",
      stock: "in-stock",
    },
  ],
  winter: [
    {
      id: "ws1",
      title: "Wool Sweater",
      image: "https://placehold.co/600x400.png",
      price: 79.99,
      vendorName: "WinterWardrobe",
      stock: "in-stock",
    },
    {
      id: "ws2",
      title: "Thermal Leggings",
      image: "https://placehold.co/600x400.png",
      price: 49.99,
      vendorName: "WarmEssentials",
      stock: "in-stock",
    },
    {
      id: "ws3",
      title: "Puffer Jacket",
      image: "https://placehold.co/600x400.png",
      price: 129.99,
      vendorName: "OuterwearPlus",
      stock: "in-stock",
    },
    {
      id: "ws4",
      title: "Knit Beanie",
      image: "https://placehold.co/600x400.png",
      price: 24.99,
      vendorName: "AccessoriesHub",
      stock: "in-stock",
    },
    {
      id: "ws5",
      title: "Fleece Gloves",
      image: "https://placehold.co/600x400.png",
      price: 19.99,
      vendorName: "WinterAccessories",
      stock: "in-stock",
    },
  ],
  festival: [
    {
      id: "fs1",
      title: "Sequin Top",
      image: "https://placehold.co/600x400.png",
      price: 59.99,
      vendorName: "FestivalFashion",
      stock: "in-stock",
    },
    {
      id: "fs2",
      title: "Fringe Vest",
      image: "https://placehold.co/600x400.png",
      price: 69.99,
      vendorName: "BohoChic",
      stock: "in-stock",
    },
    {
      id: "fs3",
      title: "Metallic Shorts",
      image: "https://placehold.co/600x400.png",
      price: 49.99,
      vendorName: "FestivalFashion",
      stock: "in-stock",
    },
    {
      id: "fs4",
      title: "Body Glitter",
      image: "https://placehold.co/600x400.png",
      price: 14.99,
      vendorName: "GlitterGlam",
      stock: "in-stock",
    },
    {
      id: "fs5",
      title: "Platform Boots",
      image: "https://placehold.co/600x400.png",
      price: 99.99,
      vendorName: "FootwearPlus",
      stock: "in-stock",
    },
  ],
  rain: [
    {
      id: "rs1",
      title: "Waterproof Jacket",
      image: "https://placehold.co/600x400.png",
      price: 89.99,
      vendorName: "RainReady",
      stock: "in-stock",
    },
    {
      id: "rs2",
      title: "Rain Boots",
      image: "https://placehold.co/600x400.png",
      price: 69.99,
      vendorName: "FootwearPlus",
      stock: "in-stock",
    },
    {
      id: "rs3",
      title: "Umbrella",
      image: "https://placehold.co/600x400.png",
      price: 29.99,
      vendorName: "RainAccessories",
      stock: "in-stock",
    },
    {
      id: "rs4",
      title: "Waterproof Backpack",
      image: "https://placehold.co/600x400.png",
      price: 59.99,
      vendorName: "BagWorld",
      stock: "in-stock",
    },
    {
      id: "rs5",
      title: "Quick-Dry Pants",
      image: "https://placehold.co/600x400.png",
      price: 64.99,
      vendorName: "RainReady",
      stock: "in-stock",
    },
  ],
}

// Customer Favorite Products
export const customerFavoriteProducts: ProductCardProps[] = [
  {
    id: "cf1",
    title: "Signature Jeans",
    image: "https://placehold.co/600x400.png",
    price: 89.99,
    vendorName: "DenimCo",
    badge: "unique",
    stock: "in-stock",
  },
  {
    id: "cf2",
    title: "Everyday Tee",
    image: "https://placehold.co/600x400.png",
    price: 29.99,
    vendorName: "BasicEssentials",
    badge: "unique",
    stock: "in-stock",
  },
  {
    id: "cf3",
    title: "Comfort Sneakers",
    image: "https://placehold.co/600x400.png",
    price: 79.99,
    vendorName: "FootwearPlus",
    badge: "unique",
    stock: "in-stock",
  },
  {
    id: "cf4",
    title: "Classic Hoodie",
    image: "https://placehold.co/600x400.png",
    price: 59.99,
    vendorName: "CasualWear",
    badge: "unique",
    stock: "in-stock",
  },
]
